//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $rootnamespace$.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$rootnamespace$.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your quintessential app description page..
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ChangePasswordModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ChangePasswordModel_ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("ChangePasswordModel_ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePasswordModel_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ChangePasswordModel_NewPassword_StringLength {
            get {
                return ResourceManager.GetString("ChangePasswordModel_NewPassword_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePasswordModel_OldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your quintessential contact page..
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text came from the resource file. how cool is that..
        /// </summary>
        public static string Demonstration_Alert {
            get {
                return ResourceManager.GetString("Demonstration_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify this template to jump-start your ASP.NET application.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Global_BackToList {
            get {
                return ResourceManager.GetString("Global_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Global_Create {
            get {
                return ResourceManager.GetString("Global_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Global_CreateNew {
            get {
                return ResourceManager.GetString("Global_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Global_DeleteConfirm {
            get {
                return ResourceManager.GetString("Global_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Global_Details {
            get {
                return ResourceManager.GetString("Global_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Global_Edit {
            get {
                return ResourceManager.GetString("Global_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Global_Save {
            get {
                return ResourceManager.GetString("Global_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginModel_Password {
            get {
                return ResourceManager.GetString("LoginModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LoginModel_RememberMe {
            get {
                return ResourceManager.GetString("LoginModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name foo bar baz.
        /// </summary>
        public static string LoginModel_UserName {
            get {
                return ResourceManager.GetString("LoginModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code52 i18n Demo site.
        /// </summary>
        public static string Logo_Title {
            get {
                return ResourceManager.GetString("Logo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ASP.NET MVC Application.
        /// </summary>
        public static string Master_SiteTitle {
            get {
                return ResourceManager.GetString("Master_SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Menu_Books {
            get {
                return ResourceManager.GetString("Menu_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string RegisterModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("RegisterModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string RegisterModel_ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("RegisterModel_ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterModel_Password {
            get {
                return ResourceManager.GetString("RegisterModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string RegisterModel_Password_StringLength {
            get {
                return ResourceManager.GetString("RegisterModel_Password_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string RegisterModel_UserName {
            get {
                return ResourceManager.GetString("RegisterModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Social_Facebook {
            get {
                return ResourceManager.GetString("Social_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Social_Twitter {
            get {
                return ResourceManager.GetString("Social_Twitter", resourceCulture);
            }
        }
    }
}
